name = "Cabaret"
description = "A clean, responsive, opinionated, template with red accents, used for halostatue.ca"
license = "Apache 2.0"
licenselink = "https://github.com/halostatue/hugo-cabaret/blob/master/LICENSE.md"
source_repo = "http://github.com/halostatue/hugo-cabaret"
version = "1.4"
tags = ["cabaret", "redlounge", "red", "raleway", "libre baskerville", "blog", "gallery"]
features = ["blog", "gallery", "series", "composable" ]
min_version = 0.14

[author]
    name = "Austin Ziegler"
    homepage = "http://www.halostatue.ca/"

[original]
    name = "Tom Maiaroto"
    homepage = "http://www.shift8creative.com"
    repo = "http://github.com/tmaiaroto/hugo-redlounge"
